docs/team/cloud7050.md
docs/team/johndoe.md

This is another quick PR to add my PPP skeleton.

[Week 7] TP Iterations 4: PPP

---

docs/DeveloperGuide.md

This implements the basic use cases that the user may face shall as adding contacts, deleting contacts and listing contacts.
Closes #13

[Week 7] TP Iterations 5: DG Use Cases

---

docs/_sass/minima/_base.scss

Change the header of top navigation bar of our project website to our project name.
Closes #9

[Week 7] TP Iterations 2B: Site-Wide Settings

---

docs/AboutUs.md

Add my photo and update AboutUs info.

[Week 7] TP Iterations 2A: AboutUs

---

docs/team/mamayuan.md

[Week 7] TP Iterations 4: PPP 

---

README.md

Update README, in particular add acknowledgement of the original source 
code.
Closes #8.

[Week 7] TP Iterations 2A: README

---

docs/DeveloperGuide.md

Update DG
Added target user profile, value proposition, and the user stories we
identified.
Closes #12.

[Week 7] TP Iterations 5: DG User Stories, Target User Profile, Value Proposition

---

docs/index.md

This replaces the information in the main page of our website to include our project information,
Closes #57

Update index.md to include information about our project

---

docs/DeveloperGuide.md

This small PR adds Jekyll as an NFR in the DG.
Closes #50.

Add Jekyll NFR

---

docs/DeveloperGuide.md

This small PR adds another NFR.

Add merged branch preservation NFR

---

docs/DeveloperGuide.md
docs/UserGuide.md

Renaming Person to Contact in the documentation.
[Closes #30.]

Rename Person to Contact

---

README.md
docs/DeveloperGuide.md
docs/index.md

This PR um... also tackles #79. While merging `README.md` with `index.md` and adding an NFR.

Add README NFR, merge README with index.md

---

docs/UserGuide.md
src/main/java/swe/context/logic/Messages.java
src/main/java/swe/context/model/alternate/AlternateContact.java
src/main/java/swe/context/model/util/SampleContactsUtil.java
src/test/data/JsonContactsStorageTest/duplicateContacts.json
src/test/data/JsonContactsStorageTest/typicalContacts.json
src/test/java/swe/context/model/alternate/AlternateContactTest.java
src/test/java/swe/context/storage/JsonContactTest.java
src/test/java/swe/context/testutil/TestData.java

Update `AlternateContact.java` regex so that the format is now `AlternateContact: Name` instead of `AlternateContact@Name`.
Update UG to include guide on formatting for alternate contacts.
This is a continuation of #124.

Update Alternate Contact

---

docs/UserGuide.md

Flesh out UG for filter (add examples). 
Closes #156.

Flesh out UG for filter

---

docs/UserGuide.md

Make duplicate handling completely precise. 
Closes #179.

Make duplicate handling precise

---

docs/DeveloperGuide.md
docs/UserGuide.md

Specified `INDEX` we use is 1-based.
Added a command summary table at the end.

Enhancement of UG

---

docs/UserGuide.md

Update UG to explain 1-indexing. 
Closes #172.

Better explanation on whether Index is zero/one-based

---

docs/UserGuide.md
docs/team/cloud7050.md

This PR adds the initial draft for my PPP. Sections I wish to include and their initial contents have been written, except for "Enhancements implemented". I am aiming to get this merged first to count for this week's deliverable, and will finish it up separately.
**I may not be around before the 4pm deadline to help ensure PPP drafts are all merged. If you guys could help (review and) merge all the PPP drafts before then, that would be great!**
Works towards #185.

Add my PPP draft

---

docs/UserGuide.md

Include support for manual editing and save file transfer in UG.
Closes #188

Update UG to show support for edit save data manually and transferring save file

---

src/test/java/swe/context/commons/core/ConfigTest.java
src/test/java/swe/context/commons/core/GuiSettingsTest.java
src/test/java/swe/context/model/alternate/AlternateContactTest.java
src/test/java/swe/context/model/contact/ContactTest.java
src/test/java/swe/context/model/contact/EmailTest.java
src/test/java/swe/context/model/contact/NameTest.java
src/test/java/swe/context/model/contact/NoteTest.java
src/test/java/swe/context/model/contact/PhoneTest.java
src/test/java/swe/context/model/tag/TagTest.java

Add more tests to improve codecov.

Add more tests

---

docs/UserGuide.md

Solution was to copy-paste unicode character from here https://www.compart.com/en/unicode/U+2800
Closes #198.

Force spacing in UG

---

docs/UserGuide.md

Explain in UG that 'empty' fields are not allowed, just to be safe!

Explain that 'empty' fields are not allowed

---

src/main/java/swe/context/ui/CommandBox.java
src/main/java/swe/context/ui/CommandBoxHistory.java
src/test/java/swe/context/ui/CommandBoxHistoryTest.java

Simplify code to improve code quality.

Simplify code to improve code quality

---

docs/DeveloperGuide.md
docs/team/cloud7050.md

Closes #161, closes #150, closes #166, closes #178.

Update planned enhancements

---

docs/UserGuide.md

Documentation review
